Output ruby-bootstrap-scrapper.gif
Set FontSize 18
Set Height 720
Set Width 1280
Sleep 1s
Type "aieditor scraper.rb"
Enter
Sleep 1s
Type "/"
Type "Write a ruby shell script (include a shebang) that scrapes https://bbc.com for headlines. Headlines are in h3 tags. Remember to strip the text."
Sleep 3s
Enter
Sleep 20s
Type "a"
Sleep 5s
Type "s"
Sleep 1s
Ctrl+c
Type "chmod +x scraper.rb"
Enter
Type "./scraper.rb"
Enter
Sleep 10s
